name: MLops CI

on: 
    workflow_dispatch: {}

jobs:
  e2e_mlops_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Processing Tests
        run: |
          python src/data/run_processing.py  \
            --input data/raw/house_data.csv  \
            --output data/processed/cleaned_house_data.csv
            
      - name: Do Feature Engineering
        run: |
          python src/features/engineer.py  \
            --input data/processed/cleaned_house_data.csv  \
            --output data/processed/featured_house_data.csv  \
            --preprocessor models/trained/preprocessor.pkl
            
      - name: Start MLflow Server
        run: |
          mlflow server --host 0.0.0.0 --port 5555 \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root /tmp/mlruns &
         
      - name: Train the Model
        run: |
          python src/models/train_model.py  \
            --config configs/model_config.yaml  \
            --data data/processed/featured_house_data.csv  \
            --models-dir models  \
            --mlflow-tracking-uri http://localhost:5555

      - name: Cleaning up MLflow
        run: |
          pkill -f "mlflow server" || true

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/fastapi:${{ github.sha }}
          context: "."
          file: "Dockerfile"